// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaibnqjudhrlrhxbhkeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhaWJucWp1ZGhybHJoeGJoa2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTUxNzAsImV4cCI6MjA2ODM5MTE3MH0.gRTG0MXbvRKSzpRo6HPYTQbzBl6WnGs31EGD4dhMxy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});